In [4]:
import pandas as pd

df = pd.read_csv(
    "/Users/shivampatel/Downloads/End-to-End-Data-Analytics-Project-SQL-Tableau-Full-Course-2026-main/Walmart Sales 2024 -2025.csv"
)

In [5]:
print(df.shape)

(1000, 22)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   invoice_id        1000 non-null   str
 1   branch            1000 non-null   str
 2   city              1000 non-null   str
 3   customer_type     1000 non-null   str
 4   gender            1000 non-null   str
 5   product_name      1000 non-null   str
 6   product_line      1000 non-null   str
 7   unit_price        1000 non-null   float64
 8   quantity          1000 non-null   int64
 9   vat               1000 non-null   float64
 10  total             1000 non-null   float64
 11  date              1000 non-null   str
 12  time              1000 non-null   str
 13  payment           1000 non-null   str
 14  cogs              1000 non-null   float64
 15  gross_margin_pct  1000 non-null   float64
 16  gross_income      1000 non-null   float64
 17  rating            1000 non-null   float64
 18  time_of_day       1000 non-null   str
 19  day_name          1000 non-null   str
 20  month_name        1000 non-null   str
 21  product_category  1000 non-null   str
dtypes: float64(7), int64(1), str(14)
memory usage: 172.0 KB

In [7]:
df.describe()

,unit_price,quantity,vat,total,cogs,gross_margin_pct,gross_income,rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.000000
mean,55.672130,5.519000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.972200
std,26.494628,2.935687,11.708825,245.885335,234.17651,1.777246e-15,11.708825,1.717713
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.000000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.500000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.000000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.500000
max,99.960000,14.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,9.900000

In [8]:
df.isnull().sum()

invoice_id          0
branch              0
city                0
customer_type       0
gender              0
product_name        0
product_line        0
unit_price          0
quantity            0
vat                 0
total               0
date                0
time                0
payment             0
cogs                0
gross_margin_pct    0
gross_income        0
rating              0
time_of_day         0
day_name            0
month_name          0
product_category    0
dtype: int64

In [9]:
df.head()

,invoice_id,branch,city,customer_type,gender,product_name,product_line,unit_price,quantity,vat,...,time,payment,cogs,gross_margin_pct,gross_income,rating,time_of_day,day_name,month_name,product_category
0,101-17-6199,Baner,Pune,Prime,Male,Nescafe Coffee,Food and beverages,45.79,7,16.0265,...,19:44:00,Credit card,320.53,4.761905,16.0265,7.0,Evening,Wednesday,March,Good
1,101-81-4070,Gachibowli,Hyderabad,Elite,Female,Face Wash,Health and beauty,62.82,2,6.2820,...,12:36:00,Ewallet,125.64,4.761905,6.2820,4.9,Afternoon,Thursday,January,Bad
2,102-06-2002,Bandra,Mumbai,Elite,Male,Gym Bag,Sports and travel,25.25,14,6.3125,...,17:52:00,Cash,126.25,4.761905,6.3125,6.1,Evening,Wednesday,March,Bad
3,102-77-2261,Baner,Pune,Elite,Male,Face Wash,Health and beauty,65.31,7,22.8585,...,18:02:00,Credit card,457.17,4.761905,22.8585,4.2,Evening,Tuesday,March,Good
4,105-10-6182,Powai,Mumbai,Basic,Male,Sunglasses,Fashion accessories,21.48,2,2.1480,...,12:22:00,Ewallet,42.96,4.761905,2.1480,6.6,Afternoon,Wednesday,February,Bad

In [10]:
df.columns

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_name', 'product_line', 'unit_price', 'quantity', 'vat',
       'total', 'date', 'time', 'payment', 'cogs', 'gross_margin_pct',
       'gross_income', 'rating', 'time_of_day', 'day_name', 'month_name',
       'product_category'],
      dtype='str')

In [11]:
   from getpass import getpass
   from sqlalchemy import create_engine

   password = getpass("Enter DB password: ")
   engine = create_engine(f"postgresql+psycopg2://postgres:{password}@localhost:5432/walmart")

Enter DB password:  ········

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.to_sql(
    "sales",
    engine,
    if_exists="append",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!